# Generated by Django 4.0.5 on 2022-07-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_applystatus_job_post_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applystatus',
            name='job_post_activity',
        ),
        migrations.AddField(
            model_name='applystatus',
            name='job_post_activity',
            field=models.ManyToManyField(null=True, to='post.jobpostactivity'),
        ),
    ]
