# Generated by Django 4.0.5 on 2022-07-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_applystatus_job_post_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applystatus',
            name='job_post_activity',
        ),
        migrations.AddField(
            model_name='jobpostactivity',
            name='job_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.applystatus'),
        ),
    ]
