# Generated by Django 4.0.5 on 2022-07-22 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0009_remove_applystatus_job_post_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEvaluationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stauts', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'job_evaluation_status',
            },
        ),
        migrations.CreateModel(
            name='JobPostActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job_post_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.jobpostactivity')),
                ('job_valuation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.jobevaluationstatus')),
            ],
            options={
                'db_table': 'job_post_activity_log',
            },
        ),
    ]
