# Generated by Django 4.0.5 on 2022-07-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_jobevaluationstatus_jobpostactivitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobevaluationstatus',
            old_name='stauts',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='jobpostactivitylog',
            old_name='job_valuation',
            new_name='job_evaluation',
        ),
    ]
